### ISSUE TITLE
Else condition evaluated even if iff is true

### ISSUE THREAD

**Issue by juliendangers** [FGRibreau/if-exp#1]
Following snippet will throw if *myvar* is null, or undefined

```
var iff = require('if-exp');
var myvar = null;
var res = iff (!myvar)
    .then("fail")
  .elseIff(myvar.someAttribute) // will throw
    .then("ok");

console.log(res);
```

**Comment by FGRibreau** [comment]
@juliendangers indeed, because `!myvar` and `myvar.someAttribute` are evaluated one after the other. So either use `myvar && myvar.someAttribute` or send a PR to support lazy function evaluation as conditional :)
